language: php

php:
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=^3.3
  - SYMFONY_VERSION=^4.0
  - SYMFONY_VERSION=dev-master

cache:
  directories:
    - $COMPOSER_CACHE_DIR

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION=^4.0
    - php: 7.0
      env: SYMFONY_VERSION=dev-master

before_install:
  - travis_retry composer selfupdate

before_script:
  - if [ "$SYMFONY_VERSION" = "^4.0" ]; then composer config minimum-stability dev; composer config prefer-stable true; fi
  - travis_wait composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - travis_wait composer install --dev --prefer-source

script: ./vendor/bin/phpunit
